### ISSUE TITLE
[HELP] I installed it but when i go manage/login.php it gives me error 500

### ISSUE THREAD

**Issue by MiRO92** [82Flex/WEIPDCRM#52] opened 2016-02-02 08:38 UTC
I installed it but when i go manage/login.php it gives me error 500
please help me fixing this 

thank u

**Comment by Hintay** [comment] 2016-02-02 08:56
Please post detailed information about your server from PHP probe.

**Comment by MiRO92** [comment] 2016-02-02 09:24
what do u mean by "PHP probe"?

any way this is my server info
![capture](https://cloud.githubusercontent.com/assets/3205572/12744902/da5a8baa-c9a7-11e5-90a3-f120fa094ec1.PNG)

**Comment by Hintay** [comment] 2016-02-02 09:34
PHP Prober, like iProber and Yahei-PHP Prober etc. Anyway can you post your phpinfo()?

**Comment by MiRO92** [comment] 2016-02-02 09:39
go to this 

http://miro92.com/test.php

**Comment by RKO1195** [comment] 2016-02-02 13:10
Hi

I'm having this same issue, everything said it was good on install and everything was writeable like it all passed on screen like his above and it shows same blank page on settings.php and release.php and login.php it won't let me set them up after it installs cause it won't let me login. 

I'm on php 5.5

**Comment by Hintay** [comment] 2016-02-02 14:20
That seems like a issue for open_basedir, I will try to fix that.

**Comment by RKO1195** [comment] 2016-02-02 14:42
Here is my php info if it helps but I've tried everything I know and can't get it to work lol.. I'm not great at this stuff but trying.. 

http://rko1195.com/phpinfo.php/

**Comment by RKO1195** [comment] 2016-02-02 15:00
Thank you! 

If you know anything I can try let me know and I will

**Comment by RKO1195** [comment] 2016-02-02 17:29
Ok let me ask this ? When it installs and tells you to make a username and password for your login it shows your repo URL there mine has two // after main is this wrong ? Or is it suppose to have that ? 

https://www.dropbox.com/s/behbtsclvfvz1u8/Repo%20manager.png?dl=0

**Comment by MiRO92** [comment] 2016-02-02 17:33
> let me ask this ? When it installs and tells you to make a username and password for your login it shows your repo URL there mine has two // after main is this wrong ? Or is it suppose to have that ?

https://www.dropbox.com/s/behbts

 i got the same thing but i removed the extra "/" and completed the install

**Comment by Hintay** [comment] 2016-02-03 09:39
I can't reproduce this issue in the local, everything is work fine for me.
So could someone provide a test account for the server with this issue?

**Comment by MiRO92** [comment] 2016-02-03 13:19
> I can't reproduce this issue in the local, everything is work fine for me.
> So could someone provide a test account for the server with this issue?

i sent u email, please check it

**Comment by RKO1195** [comment] 2016-02-03 15:47
Yea I can if you still need it ?  Let me know

 thanks

**Comment by Hintay** [comment] 2016-02-04 06:43
Fixed in commit ebe5e2a (hopefully), please update to the latest version and feedback in time :).

**Comment by RKO1195** [comment] 2016-02-04 06:56
Thank you so so much :)   Going try it here shortly just got home from work

**Comment by RKO1195** [comment] 2016-02-04 07:32
It's fixed 😊😊 works first try 

Thanks very much bud 

Sending donation this weekend

**Closed as completed** 2016-02-04 08:39 UTC
Labels: bug

**Comment by Cydiaptso** [comment] 2016-06-25 20:33
作者您好，楼主的error 500报错记得是他的服务器版本太高，DCRM好像仅支持使用php 5.3版才能正常登陆。

Server's PHP version changed to 5.3（这个是Google翻译给楼主的看的）
